feat(new drives) `Walmart`
openfoodfacts/DriveOFF pull request #9
Opened 2024-04-04 02:31 UTC by KevinBon

### What

Adding `Walmart` to the list of "drives".

### Screenshot

| Example | Before | After |
|:-:|:-:|:-:|
| https://www.walmart.com/ip/Duncan-Hines-Chewy-Fudge-Chocolate-Brownie-Mix-Family-Size-18-3-oz/10309845?athbdg=L1600 | ![image](https://github.com/openfoodfacts/DriveOFF/assets/1910927/f4e54b9f-3eaa-486f-804e-a0cc84cbdb52) | ![image](https://github.com/openfoodfacts/DriveOFF/assets/1910927/7bb38ac5-1e13-4df0-9223-00ecedf6883f) |
| https://www.walmart.com/ip/Nutella-Hazelnut-Spread-with-Cocoa-for-Breakfast-13-oz-Jar/10451273?athbdg=L1200&from=/search | ![image](https://github.com/openfoodfacts/DriveOFF/assets/1910927/9db02d4e-5a33-44d7-abfd-19e81ad4c5cc) | ![image](https://github.com/openfoodfacts/DriveOFF/assets/1910927/6937f64d-e981-4da5-aaa9-20c83195a6c8)) |

2024-04-17 21:15 UTC, ghost requested changes
Thank you for your participation and sorry to not have taken the time to make a proper documentation before burning out. ^^

Just a few details to fix.

2024-09-26 10:10 UTC, teolemon commented
@KevinBon @clovfr, it would be nice to have this one fixed and merged

2025-06-12 20:40 UTC, ghost commented
Thank you for your interest in this project and sorry for the wait.

But I'm closing this PR without a maintainer for this shop.

2025-06-12 20:40 UTC, closed without merging

2025-06-14 07:24 UTC, teolemon commented
@clovfr was it already broken ?
I would assume the person making the PR @KevinBon in that case, becomes the de-facto maintainer for the shop.
Worst case scenario it does not work for that peculiar website.

2025-06-14 15:39 UTC, ghost commented
Yes it was broken, read the freaking log.

I requested changes more than one year ago without no flipping reply since. PR rejected. Period.

2025-06-14 15:45 UTC, ghost commented
If @KevinBon is still willing to participate, he's welcome to PR again, but please, from actual working branch this time.